### ISSUE TITLE
Module.cwrap does not exist

### ISSUE THREAD

**Issue by a-x-** [raphamorim/wasm-and-rust#1]
instead of Module.cwrap('fn_name')
I found: Module._fn_name()

rustc -V
rustc 1.24.1 (d3ae9a9e0 2018-02-27)

emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.35
clang version 5.0.0 (https://github.com/kripken/emscripten-fastcomp-clang.git 49828f21d7a2e4587b2749e0e3940bb85f932abb) (https://github.com/kripken/emscripten-fastcomp.git 0a60b19dc4b9068c52b952598a2636dc370e56ce) (emscripten 1.37.35 : 1.37.35)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Users/mxtnr/emsdk-portable/clang/fastcomp/build_incoming_64/bin
INFO:root:(Emscripten: Running sanity checks)

**Comment by raphamorim** [comment]
I believe #5 should fix it. Let me know it keeps failing.
