### ISSUE TITLE
Problems loading js

### ISSUE THREAD

**Issue by samghelms** [raphamorim/wasm-and-rust#2]
Heads up - for some reason, the site.js file set all of the wasm link names to things like 'wasm_demo.{asm.js,.wasm}' instead of the 'site.wasm' needed to actually load the files. This meant the demo didn't work for me until I changed these names.

**Comment by blogscot** [comment]
Hi @samghelms, I originally came across this example in hoverbear's blogpost [here](https://hoverbear.org/2017/04/06/the-path-to-rust-on-the-web/). Hoverbear explains in his (I presume he's a dude) blogpost:

> Next we need to set up some way to get the generated files from the target/ folder into the site/ folder. make is a good solution for this, so let’s make a Makefile.

This makefile moves and _**renames**_ the "*.wasm" and "*.asm.js" to site.wasm and site.js respectively.  

Could this explain your problem? 🤔

**Comment by raphamorim** [comment]
Fixed in #6
