### ISSUE TITLE
console output: "on the web, we need the wasm binary to be preloaded"

### ISSUE THREAD

**Issue by binary132** [raphamorim/wasm-and-rust#3]
FF Nightly 61.0a1 (2018-04-12) (64-bit) for Ubuntu.

When running this, I get the following output:
```
uncaught exception: abort("on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)"). Build with -s ASSERTIONS=1 for more info.
```
Related to this issue?  https://github.com/WebAssembly/binaryen/issues/867#issuecomment-270286201

**Comment by raphamorim** [comment]
I believe #6 should fix it, let me know if it's still failing.
